Added Mobile Stepper component
pxblue/react-native-showcase-demo pull request #89
Opened 2023-10-10 07:47 UTC by manojleaton

Fixes #BLUI-4373 .

#### Changes proposed in this Pull Request:

- Updated the kitchen sink component with MobileStepper example.

#### Screenshots / Screen Recording (if applicable)

<img width="328" alt="Screenshot 2023-10-10 at 1 12 51 PM" src="https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/130662346/4cf9e522-7b6f-4f13-bd48-52728dbf7a6c">

#### To Test:

- yarn start

#### Any specific feedback you are looking for?

-

2023-10-10 11:34 UTC, surajeaton reviewed
Please resolve the conflicts.

2023-10-10 20:02 UTC, huayunh reviewed
any chance you can resolve that error in the CI build? Changes look good otherwise

2023-10-11 20:04 UTC, JeffGreiner-eaton commented
comment for how these should be tested. I'm currently in component library on branch release/md3 and the showcase is on feature/4373-mobile-stepper-md3 branch. When I run iOS I receive this error. Am I missing something to spin this up?

ERROR  Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `MobileStepperExample`.
    in MobileStepperExample (created by KitchenSink)

<img width="411" alt="image" src="https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/119693939/de5e0608-e4c7-4197-b24e-5ae53be1a62b">

2023-10-12 11:05 UTC, manojleaton commented
> comment for how these should be tested. I'm currently in component library on branch release/md3 and the showcase is on feature/4373-mobile-stepper-md3 branch. When I run iOS I receive this error. Am I missing something to spin this up?
> 
> ERROR Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `MobileStepperExample`. in MobileStepperExample (created by KitchenSink)
> 
> <img alt="image" width="411" src="https://user-images.githubusercontent.com/119693939/274402562-de5e0608-e4c7-4197-b24e-5ae53be1a62b.png">
You need to checkout to the branch `feature/4373-mobileStepper-MD3` in component library.

2023-10-12 12:01 UTC, JeffGreiner-eaton commented
> > comment for how these should be tested. I'm currently in component library on branch release/md3 and the showcase is on feature/4373-mobile-stepper-md3 branch. When I run iOS I receive this error. Am I missing something to spin this up?
> > ERROR Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> > Check the render method of `MobileStepperExample`. in MobileStepperExample (created by KitchenSink)
> > <img alt="image" width="411" src="https://user-images.githubusercontent.com/119693939/274402562-de5e0608-e4c7-4197-b24e-5ae53be1a62b.png">
> 
> You need to checkout to the branch `feature/4373-mobileStepper-MD3` in component library.

it was something with cache on my end, running now. thanks

2023-10-12 16:58 UTC, JeffGreiner-eaton reviewed
looks good just run lint/prettier

2023-10-13 06:00 UTC, ektaghag-eaton approved these changes

2023-10-13 06:02 UTC, ektaghag-eaton requested changes

2023-10-13 06:02 UTC, ektaghag-eaton commented on md3-themes/MD3BluiLightTheme.ts
> +        disabled: '#192024',
We need to update colour in the dark theme.

2023-10-13 09:24 UTC, ektaghag-eaton approved these changes

2023-10-13 09:24 UTC, merged